### ISSUE TITLE
No Camera Detected After Installation

### ISSUE THREAD

**Issue by itsthebypassline** [goodtohear/BeatSheetStudio#102]
**Describe the bug**
I installed the beta a few minutes ago. Install Virtual Camera and Virtual Mic. Rebooted. The app says I still need the camera extension, even though as you'll see in the video, CueCam has both mic and camera permissions.

**To Reproduce**
1. Install CueCam
2. Install Virtual Mic and Virtual Camera
3. Reboot
4. CueCam says Camera Extension still needed.

https://github.com/goodtohear/BeatSheetStudio/assets/146373387/187acf1f-91b4-4a19-8964-91db56c1bfe5

**Comment by itsthebypassline** [comment]
Interestingly (maybe this is expected?) when I launch CueCam it automatically launches Camo Studio...

**Comment by michaelforrest** [comment]
When you install the camera extension you need to press the little "Allow" button that the "Settings" button links to inside CueCam. You're looking at the camera inputs there but the setting you need is further down the main "Privacy & Security" page. 
I probably need to add a video clip showing what all of this should look like, because on my machine after I click "Allow" it shows an unrelated and misleading "System Extensions Disabled" message!

**Comment by itsthebypassline** [comment]
Yup, I’d done that too.

Thanks,
David

**Comment by michaelforrest** [comment]
I think we resolved this? Closing.
